### ISSUE TITLE
fabにエラー

### ISSUE THREAD

**Issue by Naomath** [Naomath/Myapp_for_app_contest_new#3]

**Comment by Naomath** [comment]
08-28 23:02:53.901 22724-22724/com.lifeistech.naoto.myapplication_app_contest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                Process: com.lifeistech.naoto.myapplication_app_contest, PID: 22724
                                                                                                java.lang.IllegalStateException: Could not find a method fab(View) in the activity class com.lifeistech.naoto.myapplication_app_contest.Activity.ListGroupWordsActivity for onClick handler on view class android.support.design.widget.FloatingActionButton with id 'fab'
                                                                                                    at android.view.View$1.onClick(View.java:4008)
                                                                                                    at android.view.View.performClick(View.java:4781)
                                                                                                    at android.view.View$PerformClick.run(View.java:19874)
                                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5494)
                                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:943)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:738)
                                                                                                 Caused by: java.lang.NoSuchMethodException: fab [class android.view.View]
                                                                                                    at java.lang.Class.getMethod(Class.java:664)
                                                                                                    at java.lang.Class.getMethod(Class.java:643)
                                                                                                    at android.view.View$1.onClick(View.java:4001)
                                                                                                    at android.view.View.performClick(View.java:4781) 
                                                                                                    at android.view.View$PerformClick.run(View.java:19874) 
                                                                                                    at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5494) 
                                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:943) 
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:738)

**Comment by Naomath** [comment]
ListGroupWordsActivityのfab（グローバル変数)を押した時に出ます

**Comment by halu5071** [comment]
たぶん、fabのonclick属性にメソッドを定義してると思うけど、それが上手くいってないね

ListGroupWordsActivityのxmlで、designタブじゃなくてtextタブを開いて、fabのonclickを確認してみて。

**Comment by Naomath** [comment]
確認しましたが、それは問題ないと思います。　onclickもidからやっているので、ListGroupTwoWordsActivityにかいてあります

**Comment by halu5071** [comment]
なーるほど…

> java.lang.IllegalStateException: Could not find a method fab(View) in the activity class com.lifeistech.naoto.myapplication_app_contest.Activity.ListGroupWordsActivity for onClick handler on view class android.support.design.widget.FloatingActionButton with id 'fab'



> Caused by: java.lang.NoSuchMethodException: fab [class android.view.View]

これにあるとおり、fabっていうメソッドがメソッドとして認識されてないっぽい。

んー。確認なんだけど、fabを使うために、support libraryを入れたよね？？

**Comment by Naomath** [comment]
他のfabを使っているところでは大丈夫ですし、いれたと思います

**Comment by halu5071** [comment]
idかぶってる説は？？

**Comment by Naomath** [comment]
一回fabのidをfab79にしましたが同じエラーでした。

**Comment by Naomath** [comment]
onclickListerをインターフェイスとして実装しなくして、onclickメソッドを作ってやりました
